eta_heizung:
  host: heizfix
  port: 8080
  sensors:
    - name: "Außentemperatur"
      uri: "/112/10241/0/0/12197"
      unit: "°C"
    - name: "Gesamtverbrauch"
      uri: "/112/10021/0/0/12016"
      unit: "kg"
    - name: "Inhalt Pelletsbehälter"
      uri: "/112/10021/0/0/12011"
      unit: "kg"
    - name: "Kessel Abgas"
      uri: "/112/10021/0/0/12162"
      unit: "°C"
    - name: "Kesseltemperatur"
      uri: "/112/10021/0/0/12180"
      unit: "°C"
    - name: "Kessel soll"
      uri: "/112/10021/0/0/12001"
      unit: "°C"
    - name: "Kesseldruck"
      uri: "/112/10021/0/0/12161"
      unit: "bar"
    - name: "Lager"
      uri: "/112/10201/0/0/12015"
      unit: "kg"
    - name: "Temperatur Raum EG"
      uri: "/112/10101/0/0/12634"
      unit: "°C"
    - name: "Temperatur Raum EG soll"
      uri: "/112/10101/0/0/12127"
      unit: "°C"
    - name: "Temperatur Raum OG"
      uri: "/112/10102/0/0/12634"
      unit: "°C"
    - name: "Temperatur Raum OG soll"
      uri: "/112/10102/0/0/12127"
      unit: "°C"
    - name: "Verbrauch seit Aschebox leeren"
      uri: "/112/10021/0/0/12013"
      unit: "kg"
    - name: "Vorlauf EG"
      uri: "/112/10101/0/0/12241"
      unit: "°C"
    - name: "Vorlauf OG"
      uri: "/112/10102/0/0/12241"
      unit: "°C"
    - name: "Temperatur Warmwasser"
      uri: "/112/10111/0/0/12271"
      unit: "°C"